run-name: Build and upload CD artifacts
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Build for linux-arm64
      run: cd DiscordMessageHook && dotnet publish -r linux-arm64 /p:PublishSingleFile=true /p:SelfContained=true -o output-arm64
    - name: Upload output for linux-arm64
      uses: actions/upload-artifact@v4
      with:
        name: dmh-latest-linux-arm64-standalone
        path: DiscordMessageHook/output-arm64
        if-no-files-found: error
        overwrite: true
    - name: Build for linux-x64
      run: cd DiscordMessageHook && dotnet publish -r linux-x64 /p:PublishSingleFile=true /p:SelfContained=true -o output-x64
    - name: Upload output for linux-x64
      uses: actions/upload-artifact@v4
      with:
        name: dmh-latest-linux-x64-standalone
        path: DiscordMessageHook/output-x64
        if-no-files-found: error
        overwrite: true
    - name: Build Shorty for win-x64
      run: cd DiscordMessageHook && dotnet publish -r win-x64 /p:PublishSingleFile=true /p:SelfContained=true -o output-win-x64
    - name: Upload output for win-x64
      uses: actions/upload-artifact@v4
      with:
        name: dmh-latest-win-x64-standalone
        path: DiscordMessageHook/output-win-x64
        if-no-files-found: error
        overwrite: true
    
